server:
  port: 8003

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/baza?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: Ancicii
    password: molotov111
  jpa:
    hibernate:
      ddl-auto: update