server:
  port: 8080

app:
  name: PomozBoze
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/baza?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: rootroot
  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    prefix: classpath:/static/
    # excluded-view-names:
    # mode: HTML5
    # suffix: .html
    # template-resolver-order:
    # view-names:
  queries:
    users-query: select username, password, 1 from users where username=?
    roles-query: select u.username, r.role from users u inner join roles ur on(u.id=ur.user_id) inner join role r on(ur.role_id=r.role_id) where u.username=?
jwt:
  header: Authorization
  expires_in: 86400
  secret: y4QVubkEydX8Lfv6WqR0hz8nsdP3F2FaKDrV6pudwhaqF4QIcm0RDlkTY9aGXFY
  cookie: AUTH-TOKEN